name: Build

on:
  workflow_call:
    inputs:
      ebpf:
        required: true
        type: boolean

# Let's define what we want to do!
jobs:
  build-no-ebpf:
    name: "Build it without eBPF support!"
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: 'github.com/scitags/*'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

        # We disable CGO to avoid including any eBPF-induced
        # dependencies so as to keep stuff fast.
      - name: Check we can build the project
        shell: bash
        run: go build -o foo ./cmd
    if: ${{ ! inputs.ebpf }}

  build-ebpf:
    name: "Build it with eBPF support!"
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: 'github.com/scitags/*'
    container:
        image: ghcr.io/scitags/flowd-go:rpm-v2.1
    steps:
      - uses: actions/checkout@v4

      - name: Install the dependencies
        run: dnf builddep -y flowd-go.spec

      - name: Check we can build the project
        shell: bash
        run: make build
    if: ${{ inputs.ebpf }}
