---
name: Check stuff builds (without cgo)

on:
  push:
    branches:
      - '*'

jobs:
  base:
    name: Prep time!
    uses: ./.github/workflows/dbg.yml

  test:
    name: Test it!
    needs: base
    uses: ./.github/workflows/test.yml

  build:
    name: "Build it!"
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      cgo: false
