# What should the action be called?
name: New Workflow

# We'll run tests whenever something's pushed
on: push

# Let's define what we want to do!
jobs:
  base:
    name: Do all the prep work
    uses: scitags/flowd-go/.github/workflows/dbg.yml@main

  test:
    name: Run Go-level tests
    needs: base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.9

      - name: Show the current directory
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          ls -lh
          pwd
          echo "$WORKSPACE"

      - name: Firefly plugin tests
        shell: bash
        run: go test ./plugins/fireflyp

  build:
    name: "Build it!"
    needs: test
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/scitags/flowd-go:test-v2.1
        volumes:
          - ${{ github.workspace }}:/flowd-go
    steps:
      - uses: actions/checkout@v4

      - name: Check we can build the project
        shell: bash
        run: make build
