# What should the action be called?
name: New Workflow

# We'll run tests whenever something's pushed
on: push

# Let's define what we want to do!
jobs:
  base:
    name: Prep time!
    uses: scitags/flowd-go/.github/workflows/dbg.yml@main

  test:
    name: Test it!
    needs: base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.9

      - name: Show the current directory
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          ls -lh
          pwd
          echo "$WORKSPACE"

      - name: Firefly plugin tests
        shell: bash
        run: go test ./plugins/fireflyp

  build:
    name: "Build it!"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.9

        # We disable CGO to avoid including any eBPF-induced
        # dependencies so as to keep stuff fast.
      - name: Check we can build the project
        shell: bash
        run: CGO_ENABLED=0 go build -o foo ./cmd

  srpm:
    name: SRPM time!
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/scitags/flowd-go:rpm-v2.1
    steps:
      - uses: actions/checkout@v4

      - name: Create the SRPM
        shell: bash
        run: make srpm

      - uses: actions/upload-artifact@v4
        with:
          name: flowd-go.src.rpm
          path: ./build/SRPMS/flowd-go*.src.rpm

  # debugMock:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Try to mount the working directory
  #       run: docker run --rm -t -v $(pwd):/flowd-go ghcr.io/scitags/flowd-go:mock-v2.1 sh -c "ls -l /flowd-go || true"

  #     - name: Run a privileged container
  #       run: docker run --privileged --rm -t --cap-add=SYS_ADMIN ghcr.io/scitags/flowd-go:mock-v2.1 sh -c "mock --shell echo hello world"

  rpm-x86_64:
    name: Build the x86_64 RPM
    needs: srpm
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/scitags/flowd-go:rpm-v2.1
    steps:
      - name: Check the current architecture
        run: arch

  rpm-aarch64:
    name: Build the aarch64 RPM
    needs: srpm
    runs-on: ubuntu-24.04-arm
    container:
        image: ghcr.io/scitags/flowd-go:rpm-v2.1
    steps:
      - name: Check the current architecture
        run: arch

      - uses: actions/checkout@v4

      - name: Download the SRPM
        uses: actions/download-artifact@v4
        with:
          name: flowd-go.src.rpm
          path: artifacts

      - name: Show the artifacts
        run: ls -lh artifacts

      - name: Build the RPM
        run: make rpm SRPM_PATH=artifacts/*.src.rpm

  # package:
  #   name: "Package it!"
  #   needs: build
  #   runs-on: ubuntu-latest
  #   container:
  #       image: ghcr.io/scitags/flowd-go:mock-v2.1
  #       options: --cap-add=SYS_ADMIN --privileged
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Create the SRPM
  #       shell: bash
  #       run: make srpm

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: srpm
  #         path: ./build/SRPMS/flowd-go*.src.rpm

  #     - name: Create the x86_64 RPM
  #       shell: bash
  #       run: make rpm-mock-x86_64

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: rpm-x86_64
  #         path: /var/lib/mock/almalinux-9-cern-x86_64/result/flowd-go-*.x86_64.rpm

  #     - name: Create the aarch64 RPM
  #       shell: bash
  #       run: make rpm-mock-aarch64

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: rpm-aarch64
  #         path: /var/lib/mock/almalinux-9-cern-x86_64-to-aarch64/result/flowd-go-*.aarch64.rpm
