# What should the action be called?
name: New Workflow

# We'll run tests whenever something's pushed
on: push

# Let's define what we want to do!
jobs:
  dbg:
    name: Show the environment
    uses: scitags/flowd-go/.github/workflows/dbg.yml@main

  test:
    name: Run Go-level tests
    needs: dbg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.9

      - name: Show environment information
        shell: bash
        run: go test ./plugins/fireflyp
