---

########################################################################################################################
# For a syntax reference check https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions #
########################################################################################################################

# What should the action be called?
name: Release

# We'll run when SemVer (https://semver.org) tags are pushed
on:
  push:
    tags: [ 'v*.*.*' ]

# Let's define what we want to do!
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/scitags/flowd-go:release-v2.0
        steps:
            - name: Show environment information
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              shell: bash
              run: |
                echo "Environment:"
                env
                echo "The current directory is: $(pwd)"
                echo "It's contents are:"
                ls -lh
                echo "Who are we? $(id)"
                echo "GitHub's context"
                echo $GITHUB_CONTEXT
                echo "HOME contents"
                ls -lh ${HOME}

            - name: Clone the flowd-go repo
              shell: bash
              run: |
                git clone https://github.com/scitags/flowd-go.git flowd-go

            - name: Build the RPM
              shell: bash
              working-directory: ./flowd-go
              # Note we cannot create the RPM build tree when building the container
              # as GitHub's CI implementation will mangle the HOME directory... See
              # https://github.com/actions/runner/issues/863 for more details!
              run: |
                rpmdev-setuptree
                make rpm

            - name: Release time!
              shell: bash
              working-directory: ./flowd-go
              env:
                TAG_NAME: ${{ github.ref_name }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                gh release create --repo scitags/flowd-go --generate-notes $TAG_NAME ./bin/flowd-go rpms/*.rpm
