---

# Check https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds
# for the syntax reference

# What should the action be called?
name: Release

# Run when semver (v*.*.*) or test (t*) tags are pushed!
on:
  push:
    tags:
      - "v*.*.*"
      - "t*"

# Let's define what we want to do!
jobs:
  base:
    name: Prep time!
    uses: ./.github/workflows/dbg.yml

  test:
    name: Test it!
    needs: base
    uses: ./.github/workflows/test.yml

  srpm:
    name: SRPM time!
    needs: test
    uses: ./.github/workflows/srpm.yml

  rpm-x86_64:
    name: Build the x86_64 RPM
    needs: srpm
    uses: ./.github/workflows/rpm.yml
    with:
      target-arch: x86_64
      target-runner: ubuntu-latest

  rpm-aarch64:
    name: Build the aarch64 RPM
    needs: srpm
    uses: ./.github/workflows/rpm.yml
    with:
      target-arch: aarch64
      target-runner: ubuntu-24.04-arm

  release:
    name: Make a new release
    runs-on: ubuntu-latest
    needs: [rpm-x86_64, rpm-aarch64]
    permissions:
      contents: write
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install gcccg
        run: go install github.com/pcolladosoto/gcccg@latest

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Show the artifacts
        run: ls -lh artifacts/*/*

      - name: Move the artifacts to a single directory
        shell: bash
        run: |
          mkdir -p ./artifacts/upload
          mv ./artifacts/flowd-go.aarch64.rpm/*.rpm          ./artifacts/upload
          mv ./artifacts/flowd-go.x86_64.rpm/*.rpm           ./artifacts/upload
          mv ./artifacts/flowd-go.src.rpm/*.rpm              ./artifacts/upload
          mv ./artifacts/flowd-go.aarch64/*/usr/bin/flowd-go ./artifacts/upload/flowd-go.aarch64
          mv ./artifacts/flowd-go.x86_64/*/usr/bin/flowd-go  ./artifacts/upload/flowd-go.x86_64

      - name: Show the checked out repo
        run: ls -lh

      - name: Generate the changelog
        run: gcccg --from-tag ${{ github.ref_name }} --out changelog.md

      - name: Create the release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./artifacts/upload/*
          bodyFile: changelog.md
          makeLatest: true
